import type { Metadata } from 'next';
import { SidebarProvider } from '@/components/ui/sidebar';
import SideBar from '@/components/Shared/SideBar';

import { Cairo } from 'next/font/google';

import Nav from '@/components/Shared/Nav';
import './globals.css';
const cairo = Cairo({
  subsets: ['latin'],
  variable: '--font-primary',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${cairo.variable} font-primary antialiased`}
      >
        <Nav />
        <SidebarProvider defaultOpen={false} className="flex flex-col">
          <SideBar />
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
