import type { Metadata } from 'next';
import { Cairo } from 'next/font/google';

import Nav from '@/components/Shared/Nav';
import './globals.css';
const workSans = Cairo({
  subsets: ['latin'],
  variable: '--font-primary',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} font-primary antialiased`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
